version: 1
name: Java with Gradle
stages:
  - name: Build and test Java app
    type: ci
    spec:
      clone:
        disabled: false
      steps:
        - name: Build
          type: script
          spec:
            run: |-
              echo "Hello world"
        - name: Run Tests
          type: run_tests
          spec:
            language: Java
            build_tool: Gradle
            build_args: test
            test_reports:
              type: JUnit
              paths:
                - "**/*.xml"
            strategy:
              parallelism: 3