pipeline:
  tags: {}
  projectIdentifier: RaghavTest
  orgIdentifier: default
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: echo hello
                  identifier: echo_hello
                  template:
                    templateRef: account.DataRobottest
                    versionLabel: v1
        strategy:
          parallelism: 10
  identifier: trigger_4
  name: trigger_4
