name: 'Hello World'

description: 'Greet someone and record the time'

inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'

outputs:
  time:
    description: 'The time we greeted you'

jobs:
  run-shell-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run the shell script
        run: |
          # Replace the following line with the actual content of your shell script
          git rev-parse HEAD
